CREATE DATABASE IF NOT EXISTS LIVROS;

CREATE TABLE IF NOT EXISTS PRODUTOS (
ID INT(4), NOME VARCHAR(150), AUTOR VARCHAR(100), GENERO VARCHAR(15), NACIONALIDADE VARCHAR(25), PAGINAS INT, PRECO FLOAT);